/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IPProxyOverrides } from "./IPProxyOverrides";

export class IPProxyOverridesFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPProxyOverrides {
    return new Contract(address, _abi, signerOrProvider) as IPProxyOverrides;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "_selector",
        type: "bytes4"
      }
    ],
    name: "doesOverride",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
