/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IPProxyOverridesInterface extends Interface {
  functions: {
    doesOverride: TypedFunctionDescription<{
      encode([_selector]: [Arrayish]): string;
    }>;
  };

  events: {};
}

export class IPProxyOverrides extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IPProxyOverrides;
  attach(addressOrName: string): IPProxyOverrides;
  deployed(): Promise<IPProxyOverrides>;

  on(event: EventFilter | string, listener: Listener): IPProxyOverrides;
  once(event: EventFilter | string, listener: Listener): IPProxyOverrides;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): IPProxyOverrides;
  removeAllListeners(eventName: EventFilter | string): IPProxyOverrides;
  removeListener(eventName: any, listener: Listener): IPProxyOverrides;

  interface: IPProxyOverridesInterface;

  functions: {
    doesOverride(_selector: Arrayish): Promise<boolean>;
  };

  doesOverride(_selector: Arrayish): Promise<boolean>;

  filters: {};

  estimate: {
    doesOverride(_selector: Arrayish): Promise<BigNumber>;
  };
}
