/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IProxySideEffects } from "./IProxySideEffects";

export class IProxySideEffectsFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProxySideEffects {
    return new Contract(address, _abi, signerOrProvider) as IProxySideEffects;
  }
}

const _abi = [
  {
    inputs: [],
    name: "sideEffectAfter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [],
    name: "sideEffectBefore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];
