/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface TestSideEffectsInterface extends Interface {
  functions: {
    sideEffectAfter: TypedFunctionDescription<{ encode([]: []): string }>;

    sideEffectBefore: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class TestSideEffects extends Contract {
  connect(signerOrProvider: Signer | Provider | string): TestSideEffects;
  attach(addressOrName: string): TestSideEffects;
  deployed(): Promise<TestSideEffects>;

  on(event: EventFilter | string, listener: Listener): TestSideEffects;
  once(event: EventFilter | string, listener: Listener): TestSideEffects;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): TestSideEffects;
  removeAllListeners(eventName: EventFilter | string): TestSideEffects;
  removeListener(eventName: any, listener: Listener): TestSideEffects;

  interface: TestSideEffectsInterface;

  functions: {
    sideEffectAfter(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    sideEffectBefore(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  sideEffectAfter(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  sideEffectBefore(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    sideEffectAfter(): Promise<BigNumber>;

    sideEffectBefore(): Promise<BigNumber>;
  };
}
