/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TestSideEffects } from "./TestSideEffects";

export class TestSideEffectsFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(): Promise<TestSideEffects> {
    return super.deploy() as Promise<TestSideEffects>;
  }
  getDeployTransaction(): UnsignedTransaction {
    return super.getDeployTransaction();
  }
  attach(address: string): TestSideEffects {
    return super.attach(address) as TestSideEffects;
  }
  connect(signer: Signer): TestSideEffectsFactory {
    return super.connect(signer) as TestSideEffectsFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TestSideEffects {
    return new Contract(address, _abi, signerOrProvider) as TestSideEffects;
  }
}

const _abi = [
  {
    inputs: [],
    name: "sideEffectAfter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [],
    name: "sideEffectBefore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061027e806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80631fd025451461003b5780632063cad014610045575b600080fd5b61004361004f565b005b61004d610051565b005b565b61008f6040518060400160405280600581526020017f4166746572000000000000000000000000000000000000000000000000000000815250610091565b565b60006a636f6e736f6c652e6c6f6773ffffffffffffffffffffffffffffffffffffffff16826040516024018080602001828103825283818151815260200191508051906020019080838360005b838110156100f95780820151818401526020810190506100de565b50505050905090810190601f1680156101265780820380516001836020036101000a031916815260200191505b50925050506040516020818303038152906040527f41304fac000000000000000000000000000000000000000000000000000000007bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19166020820180517bffffffffffffffffffffffffffffffffffffffffffffffffffffffff83818316178352505050506040518082805190602001908083835b602083106101db57805182526020820191506020810190506020830392506101b8565b6001836020036101000a038019825116818451168082178552505050505050905001915050600060405180830381855afa9150503d806000811461023b576040519150601f19603f3d011682016040523d82523d6000602084013e610240565b606091505b50509050505056fea264697066735822122000cb4e4044f3504dd0cd461bbecf39c9668c3212e5c187f5ea09af3dc3d2d05564736f6c63430006020033";
