/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TestSideEffects } from "./TestSideEffects";

export class TestSideEffectsFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(): Promise<TestSideEffects> {
    return super.deploy() as Promise<TestSideEffects>;
  }
  getDeployTransaction(): UnsignedTransaction {
    return super.getDeployTransaction();
  }
  attach(address: string): TestSideEffects {
    return super.attach(address) as TestSideEffects;
  }
  connect(signer: Signer): TestSideEffectsFactory {
    return super.connect(signer) as TestSideEffectsFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TestSideEffects {
    return new Contract(address, _abi, signerOrProvider) as TestSideEffects;
  }
}

const _abi = [
  {
    inputs: [],
    name: "sideEffectAfter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [],
    name: "sideEffectBefore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102bc806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80631fd025451461003b5780632063cad014610045575b600080fd5b61004361004f565b005b61004d61008f565b005b61008d6040518060400160405280600681526020017f4265666f726500000000000000000000000000000000000000000000000000008152506100cf565b565b6100cd6040518060400160405280600581526020017f41667465720000000000000000000000000000000000000000000000000000008152506100cf565b565b60006a636f6e736f6c652e6c6f6773ffffffffffffffffffffffffffffffffffffffff16826040516024018080602001828103825283818151815260200191508051906020019080838360005b8381101561013757808201518184015260208101905061011c565b50505050905090810190601f1680156101645780820380516001836020036101000a031916815260200191505b50925050506040516020818303038152906040527f41304fac000000000000000000000000000000000000000000000000000000007bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19166020820180517bffffffffffffffffffffffffffffffffffffffffffffffffffffffff83818316178352505050506040518082805190602001908083835b6020831061021957805182526020820191506020810190506020830392506101f6565b6001836020036101000a038019825116818451168082178552505050505050905001915050600060405180830381855afa9150503d8060008114610279576040519150601f19603f3d011682016040523d82523d6000602084013e61027e565b606091505b50509050505056fea264697066735822122094b656c49e43fbd003032a1c438d0b0ed302a88317b53e6bc87be944ab2d25c564736f6c63430006020033";
