/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface TestSideEffectsRequireInterface extends Interface {
  functions: {
    sideEffectAfter: TypedFunctionDescription<{ encode([]: []): string }>;

    sideEffectBefore: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class TestSideEffectsRequire extends Contract {
  connect(signerOrProvider: Signer | Provider | string): TestSideEffectsRequire;
  attach(addressOrName: string): TestSideEffectsRequire;
  deployed(): Promise<TestSideEffectsRequire>;

  on(event: EventFilter | string, listener: Listener): TestSideEffectsRequire;
  once(event: EventFilter | string, listener: Listener): TestSideEffectsRequire;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): TestSideEffectsRequire;
  removeAllListeners(eventName: EventFilter | string): TestSideEffectsRequire;
  removeListener(eventName: any, listener: Listener): TestSideEffectsRequire;

  interface: TestSideEffectsRequireInterface;

  functions: {
    sideEffectAfter(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    sideEffectBefore(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  sideEffectAfter(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  sideEffectBefore(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    sideEffectAfter(): Promise<BigNumber>;

    sideEffectBefore(): Promise<BigNumber>;
  };
}
